apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dclaw-recruit.fullname" . }}
  labels:
    {{- include "dclaw-recruit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dclaw-recruit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dclaw-recruit.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dclaw-recruit.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
